export const S = {
  page: { minHeight:"100vh",background:"#FAFAF8",fontFamily:"'DM Sans','Segoe UI',system-ui,sans-serif",color:"#1a1a1a",padding:"0 16px" },
  container: { maxWidth:640,margin:"0 auto",paddingTop:32,paddingBottom:48 },
  header: { display:"flex",justifyContent:"space-between",alignItems:"flex-start",marginBottom:28,flexWrap:"wrap",gap:12 },
  title: { fontSize:22,fontWeight:700,margin:0,letterSpacing:"-0.02em" },
  subtitle: { fontSize:13,color:"#6b7280",margin:"4px 0 0" },
  sectionTitle: { fontSize:16,fontWeight:700,margin:"0 0 4px",letterSpacing:"-0.01em" },
  statsRow: { display:"flex",gap:10,marginBottom:24,flexWrap:"wrap" },
  statCard: { flex:"1 1 120px",background:"#fff",border:"1px solid #e5e5e3",borderRadius:12,padding:"14px 16px",display:"flex",flexDirection:"column",gap:2 },
  statLabel: { fontSize:11,color:"#6b7280",textTransform:"uppercase",letterSpacing:0.8 },
  statValue: { fontSize:22,fontWeight:700,letterSpacing:"-0.02em" },
  insightCard: { flex:"1 1 200px",background:"#fff",border:"1px solid #e5e5e3",borderRadius:10,padding:"12px 16px",display:"flex",flexDirection:"column",gap:3 },
  patternCard: { flex:"1 1 140px",background:"#fff",border:"1px solid #e5e5e3",borderRadius:10,padding:"14px 16px",display:"flex",flexDirection:"column",gap:3 },
  primaryBtn: { padding:"12px 24px",fontSize:15,fontWeight:600,background:"#1a1a1a",color:"#fff",border:"none",borderRadius:10,cursor:"pointer",fontFamily:"inherit" },
  secondaryBtn: { padding:"10px 20px",fontSize:14,fontWeight:500,background:"#fff",color:"#1a1a1a",border:"1.5px solid #e5e5e3",borderRadius:10,cursor:"pointer",fontFamily:"inherit" },
  navBtn: { padding:"8px 16px",fontSize:13,fontWeight:500,background:"#f3f4f6",color:"#374151",border:"1px solid #e5e5e3",borderRadius:8,cursor:"pointer",fontFamily:"inherit" },
  ghostBtn: { padding:"6px 12px",fontSize:13,color:"#6b7280",background:"none",border:"none",cursor:"pointer",fontFamily:"inherit" },
  badge: { display:"inline-block",padding:"3px 10px",fontSize:11,fontWeight:600,borderRadius:6,letterSpacing:0.5 },
  progressTrack: { height:4,background:"#e5e5e3",borderRadius:2,overflow:"hidden" },
  progressFill: { height:"100%",background:"#1a1a1a",borderRadius:2,transition:"width 0.3s" },
  conceptTag: { fontSize:12,color:"#6b7280",textTransform:"uppercase",letterSpacing:0.8,marginBottom:8 },
  questionText: { fontSize:18,fontWeight:500,lineHeight:1.6,margin:0,letterSpacing:"-0.01em" },
};
